FROM golang:1.22 as builder

WORKDIR /app
COPY . .
RUN go build -o baby-records-go

FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder /app/baby-records-go /usr/local/bin/app
EXPOSE 8080

CMD ["app"]

