services:
  rust-backend:
    build:
      context: ./backend/rust
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - RUST_LOG=info

  go-backend:
    build:
      context: ./backend/go
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"

  frontend-web:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USERPOLLING=true

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: baby
      POSTGRES_PASSWORD: super_secure_password
      POSTGRES_DB: baby_records
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

