services:
  rust-backend:
    build:
      context: .
      dockerfile: backend/rust/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/rust:/app
      - cargo-target:/app/target
    environment:
      - RUST_LOG=info
    working_dir: /app
    depends_on:
      - db

  go-backend:
    build:
      context: .
      dockerfile: backend/go/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend/go:/app
    working_dir: /app
    depends_on:
      - db

  frontend-web:
    build:
      context: .
      dockerfile: frontend/web/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/web:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    depends_on:
      - rust-backend
      - go-backend

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: baby
      POSTGRES_PASSWORD: super_secure_password
      POSTGRES_DB: baby_records
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  cargo-target:
  frontend_node_modules:

