FROM rust:1.81-slim as builder

WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder /app/target/release/baby-records-rust /usr/local/bin/app
EXPOSE 8000

CMD ["app"]

