# 開発環境用のRustのDockerfile
FROM rust:1.81-slim as builder

WORKDIR /app

# cargo-watch をインストール
RUN cargo install cargo-watch

COPY . /app

# 初期ビルド（キャッシュ目的）
RUN cargo build

CMD ["cargo", "watch", "-x", "run"]

