# 本番環境用のFrontendのDockerfile
FROM node:20 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install

# ビルドして本番用の静的ファイルを作成
COPY . .
RUN npm run build

# 本番環境用にNginxを使って静的ファイルを提供
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

